### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by DorothyRMartin** [blocknetdx/block-dx#170]
Install fails

```
    4  git clone https://github.com/blocknetdx/block-dx.git
    5  ls
    6  cd block-dx/
    7  npm run start-app
    8  sudo dnf install npm
    9  npm run start-app
   10  npm start
   11  history
```

9 & 10 produce 

[user@disp5602 block-dx]$ npm start

> BLOCK-DX@1.2.0 start /home/user/block-dx
> ng serve --host 0.0.0.0

```
sh: ng: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! BLOCK-DX@1.2.0 start: `ng serve --host 0.0.0.0`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the BLOCK-DX@1.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-07-26T10_26_16_505Z-debug.log
```

**Comment by TTcoinDeveloper** [comment]
I just tried 
npm install
npm start

it worked but the page was unable to load properly

**Comment by TTcoinDeveloper** [comment]
![image](https://user-images.githubusercontent.com/29513200/61958142-2bb95700-af97-11e9-8d41-76531d006013.png)

**Comment by TTcoinDeveloper** [comment]
![image](https://user-images.githubusercontent.com/29513200/61958237-573c4180-af97-11e9-998c-56838c81f153.png)

**Comment by TTcoinDeveloper** [comment]
I got a blank blue page

**Comment by magic53** [comment]
```
npm install
npm start
npm run start-app
```
Requires the Blocknet wallet with configured blockchains:
https://github.com/blocknetdx/blocknet/releases/latest

More instructions here on how to get started with Block DX:
https://docs.blocknet.co/blockdx/setup/

**Comment by DorothyRMartin** [comment]
npm run start 

Worked but only produced a blank blue page

npm run start-app (either on its own OR in a separate terminal while start app was running)
both produced error...
```
^C[user@disp5602 block-dx]$ npm run start-app

> BLOCK-DX@1.2.0 start-app /home/user/block-dx
> electron .

/home/user/block-dx/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/home/user/block-dx/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/home/user/block-dx/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/user/block-dx/node_modules/electron/cli.js:3:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! BLOCK-DX@1.2.0 start-app: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the BLOCK-DX@1.2.0 start-app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-07-26T16_16_17_568Z-debug.log

```

**Comment by TTcoinDeveloper** [comment]
I have only reviewed and tested it today and i have came accross this error
and as u can see this error tells u the problem


![image](https://user-images.githubusercontent.com/29513200/61974188-4f42c880-afbc-11e9-93cc-78808950f637.png)

**Comment by TTcoinDeveloper** [comment]
so you can therefore manually delete  /home/user/block-dx/node_modules/electron/

**Comment by HanniAbu** [comment]
If still having errors, I suggest starting from scratch.

1. git clone https://github.com/blocknetdx/block-dx.git
1. cd block-dx/
1. npm install
1. npm run start
1. npm run build (new window)
1. npm run start-app (in same window as previous step)

After the last step Electron will open and launch the app.

As stated by magic53, you will also need the [Blocknet wallet](https://github.com/blocknetdx/blocknet/releases/latest) and the wallets of the assets being traded setup and synced.

**Comment by TTcoinDeveloper** [comment]
![image](https://user-images.githubusercontent.com/29513200/61986276-82994d80-afe4-11e9-9722-0839c5f5ae97.png)


> If still having errors, I suggest starting from scratch.
> 
> 1. git clone https://github.com/blocknetdx/block-dx.git
> 2. cd block-dx/
> 3. npm install
> 4. npm run start
> 5. npm run build (new window)
> 6. npm run start-app (in same window as previous step)
> 
> After the last step Electron will open and launch the app.
> 
> As stated by magic53, you will also need the [Blocknet wallet](https://github.com/blocknetdx/blocknet/releases/latest) and the wallets of the assets being traded setup and synced.

![image](https://user-images.githubusercontent.com/29513200/61986278-888f2e80-afe4-11e9-9a4f-7b2891dcffa8.png)

**Comment by magic53** [comment]
If you're running into issues I recommend building with docker, it has a clean build environment. Otherwise make sure you're using the latest Node LTS v10.16 (npm v6.9.0): https://nodejs.org/en/download/

To build with docker:

```
cd block-dx
docker build -f Dockerfile-linux --build-arg GIT_BRANCH=master -t blocknetdx/block-dx:master .
docker run --name=blockdx -it blocknetdx/block-dx:master run build-native
docker cp blockdx:/opt/blockdx-ui/dist-native ~/
```

The executable will be in `~/dist-native/linux-unpacked` after you copy it from the docker build environment.

**Comment by TTcoinDeveloper** [comment]
BLOCK-DX compiles with no electron error on windows
