### ISSUE TITLE
"An installation of the Blocknet wallet was not found, but is required to use Block DX." But I HAVE installed the Blocknet wallet!

### ISSUE THREAD

**Issue by HeRo002** [blocknetdx/block-dx#219]
I have not found any other place where you can get help with Block DX and Blocknet wallet, so here is my problem: 
I HAVE installed Blocknet wallet, but I have put it on another partition, and not where Block DX expects to find it, so I am asked to install it... How do I get Block DX to find my Blocknet wallet installation?

**Comment by HeRo002** [comment]
Hi! Thank you for your reply.
Yes, I installed them within the last 2 days.
I was going to use them for buying DIVI, but I decided to use an ordinary exchange, so I am not going to go through the setup again now. :-) 
I could not find any reference to Discord or Telegram on the website.

**Comment by HanniAbu** [comment]
@HeRo002 What was the website you were looking at that didn't have the Discord or Telegram listed?

**Comment by HeRo002** [comment]
I didn't find any link to any kind of help forum on https://blocknet.co/

**Comment by HanniAbu** [comment]
Okay, thanks for the feedback!
